### ISSUE TITLE
Unable to Upgrade to 0.4.0

### ISSUE THREAD

**Issue by milsyobtaf** [peterdotjs/atom-synced-sidebar#5]
When trying to upgrade from 0.2.3, I'm receiving the error "Installing “synced-sidebar@0.4.0” failed." Full error output viewable at https://gist.github.com/milsyobtaf/9966b32af1aa13745cdf.

I also tried a clean install, uninstalling the package and installing it fresh, received the same error.

**Comment by peterdotjs** [comment]
looking into it

**Comment by peterdotjs** [comment]
@milsyobtaf what OS are you using? It's not reproducible on mac or windows. I had initially saw it on my mac but was resolved after xcode was installed.

**Comment by milsyobtaf** [comment]
@peterdotjs OSX 10.10.3, Xcode 6.3.2, Atom 0.207.0.
I hadn't launched Xcode in a while, so I did. It said it needed to install some packages for debugging, but of course didn't tell me what those packages were. After it installed the packages I attempted to install synced-sidebar again, but it is still failing with the same error, from inside Atom or from the command line with APM.

**Comment by peterdotjs** [comment]
@milsyobtaf I'm running with same exact specs but it is working fine. I've uninstalled and reinstalled again and still working fine. I'll try to look and see if there is any issue with runas package but for now not sure what could be causing it.

**Comment by peterdotjs** [comment]
@milsyobtaf are you still facing the same issue?

**Comment by milsyobtaf** [comment]
@peterdotjs Thanks for checking back. I was waiting to see if Atom 1.0 would magically fix this issue, but I decided to take one more look. I have now successfully installed synced-sidebar 0.4.0! The error was apparently caused by a particular quirk in my setup. The clue was in the error report (of course), on line 7, `make: *** No rule to make target`(Personal)/appsync/atom/.node-gyp/.node-gyp/0.22.0/common.gypi', needed by `Makefile'.  Stop.`

It didn't click the first time, but `(Personal)` refers to a partial folder name, rather than a proper path. I was running Atom with the .atom file symlinked into my Dropbox account in a folder I named appsync. This was symlinked into my home directory as .atom, which was working great. However I have two Dropbox accounts, a personal account and a work account. Dropbox's amazing solution to this problem is to create two Dropbox folders and name them `Dropbox (Personal)` and `Dropbox (Work)`, with a space in the file name. This works ok on most things, since OS X is generally smart enough to deal with esoteric file paths like that, but apparently whatever you are using to run the installer is not, and it was breaking as soon as it saw the space in the folder name.

I removed my .atom symlink and moved the full atom folder back into my user directory under .atom and the package installed smoothly. I'm not currently sharing my setup with another machine, so this isn't a terrible burden, I'll just have to figure out another method of backing up my config.

I haven't had issues installing any other packages or themes, so I imagine its something in the synced-sidebar install routine, but I haven't dug into Atom's underpinnings enough to know what the issue might be. Thanks for following up, let me know if I can help you debug any further, but you can consider this issue closed on my end.

**Comment by peterdotjs** [comment]
Great to hear that the issue is resolved even though you had to really dig into it. Thanks!
